README.md
src/common/interfaces.ts
src/knock.ts
src/resources/bulk_operations/index.ts
src/resources/bulk_operations/interfaces.ts
src/resources/objects/index.ts
src/resources/objects/interfaces.ts
src/resources/preferences/helpers.ts
src/resources/preferences/index.ts
src/resources/preferences/interfaces.ts
src/resources/users/index.ts
src/resources/users/interfaces.ts
src/resources/workflows/interfaces.ts

* Adds new `knock.objects` namespace and methods
* Adds new `knock.bulkOperations` namespace and method
* Deprecates `knock.preferences` in favor of `knock.users.*Preferences` methods
* Adds new `knock.users.bulk*` methods

feat: introduce objects into api and refactor preferences

---

src/common/interfaces.ts
src/resources/preferences/interfaces.ts
src/resources/users/index.ts

* Adds support for setting `conditions` on preferences
* Fixes issue with channel data typing always being a `string` (should be `any`)
* Fixes issue where preferences required *all* channel types when setting channel types

feat: preference conditions support

---

src/resources/workflows/interfaces.ts

Recipients could only be a list of ids or a list of object references, after this update, it can be both!

fix: correct recipients typing

---

src/resources/users/interfaces.ts

- `has_tenant: true` returns notifications that are scoped to any tenant
- `has_tenant: false` returns notifications that are not scoped to any tenant
- `archived: "exclude" | "include" | "only"`

feat(kno-2198): add support for 'archived' and 'has_tenant' options for the user feeds API

---

src/resources/messages/index.ts
src/resources/messages/interfaces.ts
src/resources/users/interfaces.ts

Adds `trigger_data` filter to the following endpoints:
* Message list endpoint
* User messages endpoint
* Object messages endpoint
* Message activities endpoint
* User feed endpoint

feat(kno-2630): add support for trigger_data filter

---

README.md
package.json
src/common/exceptions.ts
src/common/interfaces.ts
src/knock.ts
yarn.lock

This adds the static `Knock.signUserToken()` and introduces a few changes in how the client can be configured so that the client is aware of both the private API key and the signing key. Next up will be updating the docs with these changes.

feat(kno-3023): add Knock.signUserToken() as a JWT signing convenience method

---

src/common/interfaces.ts
src/resources/messages/index.ts
src/resources/objects/index.ts
src/resources/tenants/index.ts
src/resources/users/index.ts

* We were incorrectly using `PaginatedResponse` for things that returned `entries`
* This PR introduces a new `PaginatedEntriesResponse` to encapsulate those vs `PaginatedItemsResponse`

fix: correct pagination types for usage

---

src/resources/objects/index.ts
src/resources/objects/interfaces.ts
src/resources/users/index.ts

Adds support for fetching subscriptions as recipient for users and objects

feat(kno-3733): add support for subscription as recipient endpoints

---

src/common/interfaces.ts

This PR handles this customer issue: https://knockcustomers.slack.com/archives/C033CKE13SS/p1694900805437269
We support all channel types except for `webhooks`, which means users can't set `ChannelTypePreferences ` for them.

feat(KNO-4322): Add webhook channel type

---

src/resources/workflows/interfaces.ts

* Updates the `CreateSchedulesProps` by setting `repeats` as nullable.
* Updates the `Schedule` by setting `next_occurrence_at` as nullable.
IMPORTANT: Do not merge until we ship one-off schedule support in Control: https://github.com/knocklabs/switchboard/pull/1719

feat(KNO-4645): Update schedule interfaces

---

CHANGELOG.md
README.md
package.json
src/common/fetchClient.ts
src/knock.ts
tsconfig.json
yarn.lock

This PR makes the Node SDK compatible with edge runtimes including Vercel Edge functions. The main changes include:
1. Replace Axios with a native fetch wrapper
2. Replace jsonwebtoken with jose as jsonwebtoken uses Node APIs like Crypto which aren't supported by the edge runtime
Note: This could use a fair amount of testing, especially around error handling. Here's an repo with a test Next 13 app which has an edge function to test against: https://github.com/knocklabs/next-edge-test. You can also use `npx ts-node test.ts` to run a typescript script and run the client directly.
Post-release: Bump minor version and announce breaking change in release notes
Resolves #38

feat: support edge runtimes

---

src/resources/tenants/index.ts
src/resources/tenants/interfaces.ts
src/resources/workflows/interfaces.ts

This PR updates the following `interfaces`:
* TriggerWorkflowProperties
* CreateSchedulesProps
* UpdateSchedulesProps
Until now the `tenant` field in these interfaces was a simple `string`, but with these changes we now allow users to use a `Tenant` or `TenantWithUpsert` so they can inline identify tenants.

feat(KNO-4998): Add tenant inline identification 

---

src/knock.ts

The API typically returns an array of error messages but in some cases, returns a single error. This update checks if errors is an array or single instance. If it's a single error, it wraps it in an array so that formatting the error message works correctly in `UnprocessableEntityException`
Resolves #47

fix: handle single error responses

---

src/knock.ts

The `PUT` method was missing these headers that are necessary for a successful request.

fix(kno-5070): add headers to put request

---

src/common/fetchClient.ts
test/resources/workflows.test.ts

Phoenix expects array values in query params to be an array rather than a comma-separated list. This updated the fetch client so that it formats array params correctly.

fix: format url query params as array rather than comma-separated list

---

package.json
src/common/fetchClient.ts
src/index.ts
src/knock.ts
src/resources/slack/index.ts
src/resources/slack/interfaces.ts

Adds slack functions and also extends our url builder to work with nested objects, which we need for one of the functions in here.

feat(kno-5440): add slack functions

---

src/knock.ts

the `DeleteSubscriptionProperties` passed to `knock.objects.deleteSubscriptions` should be used in the DELETE request's body rather than the query parameters.

send delete entity in request body rather than params

---

src/common/fetchClient.ts

Undefined values were being included in the query url which was causing validation errors. This PR skips undefined values when building the query url.

fix: filter undefined values when creating the query url

---

package.json
src/knock.ts

Adds a deprecated annotation to the `notify` method

chore: add deprecated jsdoc for notify

---

src/resources/messages/interfaces.ts

Someone called out in Slack that this interface doesn't support the `workflow_categories` string array param available on the API, so I added it. My assumption here is that passing it to `knock.get` will work the same as `MessageStatus[]` so I just added the necessary typing.

chore: update list message opts interface

---

package.json
src/resources/preferences/interfaces.ts

Marks categories, workflows, and channel_types as nullable which matches the behavior of the API to match the JS client SDK.

fix: update preference set types

---

package.json
src/resources/messages/interfaces.ts

Adds engagement status, date filters, and message id query params to match what the API supports: https://docs.knock.app/reference#get-user-messages

fix: update list message types
